name: Build Size Analyzer

on:
  pull_request:

jobs:
  build-base:
    name: Build base
    runs-on: ubuntu-latest
    steps:
      - name: Check out source files
        uses: actions/checkout@v2
      with:
        ref: ${{ github.base_ref }}
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Configure Composer cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install composer deps
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest
      - name: Install npm deps
        run: npm ci
      - name: Build files
        run: npm run analyzer
    - name: Upload base stats.json
      uses: actions/upload-artifact@v2
      with:
        name: base
        path: ./build/animation/stats.json
        retention-days: 1

  build-pr:
    name: Build PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out source files
        uses: actions/checkout@v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Configure Composer cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install composer deps
        run: composer install --no-dev --prefer-dist --no-progress --no-suggest
      - name: Install npm deps
        run: npm ci
      - name: Build files
        run: npm run analyzer
    - name: Upload base stats.json
      uses: actions/upload-artifact@v2
      with:
        name: pr
        path: ./build/animation/stats.json
        retention-days: 1

  report:
    name: Generate report
    runs-on: ubuntu-latest
    needs: [build-base, build-pr]

    steps:
    - name: Checkout PR
      uses: actions/checkout@v2
    - name: Download base stats
      uses: actions/download-artifact@v2
      with:
        name: base
        path: base
    - name: Download PR stats
      uses: actions/download-artifact@v2
      with:
        name: pr
        path: pr
    - name: Get diff
      id: get-diff
      uses: NejcZdovc/bundle-size-diff@v1
      with:
        base_path: './base/stats.json'
        pr_path: './pr/stats.json'
    - name: Comment
      uses: NejcZdovc/comment-pr@v1
      with:
        file: 'comment.md'
      env:
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        OLD: ${{ steps.get-diff.outputs.base_file_string }}
        NEW: ${{ steps.get-diff.outputs.pr_file_string }}
        DIFF: ${{ steps.get-diff.outputs.diff_file_string }}
        DIFF_PERCENT: ${{ steps.get-diff.outputs.percent }}
