name: Test e2e for JS

on: [pull_request]


jobs:
  e2e:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      # setup the composer cache (vendor) with github actions cache and the cache dir defined in the previous step
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # run composer install
      - name: Install composer
        run: composer install --prefer-dist --no-progress --no-suggest

      # setup the node cache (node_modules) with github actions cache
      - name: Cache Node - npm
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-cache-
      
      - name: npm ci
        run: |
          npm ci
          
      - name: Make dev build
        run: |
          npm run build-dev
      
      - name: setup wp env
        run: |
          npm run wp-env start

      # run the node.js puppeteer script (which takes the screenshots and controls chrome)
      - run: npm run test:e2e
      
  comment-on-pr:
      name: Comment on PR with results
      if: ${{ github.head_ref && github.head_ref != null }}
      runs-on: ubuntu-latest
      needs: e2e
      env:
        CI: true
        GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
      outputs:
        pr_number: ${{ steps.get-pr-number.outputs.num }}
        comment_body: ${{ steps.get-comment-body.outputs.body }}
      steps:

        - name: Cache performance results
          uses: actions/cache@v2
          env:
            cache-name: cache-performance
          with:
            path: ./src/blocks/test/e2e/performance/performance.spec.results.json
            key: ${{ runner.os }}-performance-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-performance-${{ env.cache-name }}-
              ${{ runner.os }}-performance-
              ${{ runner.os }}-

        - name: Get PR number
          id: get-pr-number
          run: echo "::set-output name=num::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')"

        - name: Check if a comment was already made
          id: find-comment
          uses: peter-evans/find-comment@v1
          with:
            issue-number: ${{ steps.get-pr-number.outputs.num }}
            comment-author: github-actions[bot]
            body-includes: E2E test results

        - name: Get comment body
          id: get-comment-body
          run: |
            body="Average typing speed in Page/Post: $( jq '.typingSpeedAvg' src/blocks/test/e2e/performance/performance.spec.results.json )ms (WP Post is aprox 53ms)"
            body="${body//$'\n'/'%0A'}"
            echo "::set-output name=body::$body"
        - name: Create comment on PR with links to plugin builds
          if: ${{ steps.find-comment.outputs.comment-id == '' }}
          uses: peter-evans/create-or-update-comment@v1
          with:
            issue-number: ${{ steps.get-pr-number.outputs.num }}
            body: ${{ steps.get-comment-body.outputs.body }}

        - name: Update comment on PR with links to plugin builds
          if: ${{ steps.find-comment.outputs.comment-id != '' }}
          uses: peter-evans/create-or-update-comment@v1
          with:
            comment-id: ${{ steps.find-comment.outputs.comment-id }}
            edit-mode: replace
            body: ${{ steps.get-comment-body.outputs.body }}