name: Test PHP


on: [pull_request]

jobs:
  phplint:
    name: Phplint
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP version
        uses: shivammathur/setup-php@v1
        with:
          php-version: '5.6'
          extensions: simplexml
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Setup Composer cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install composer
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run PHPCS
        run: composer run lint
  phpunit:
    name: Phpunit on 7.3
    runs-on: ubuntu-latest
    container:
      image: php:7.3-apache
      env:
        NODE_ENV: production
      ports:
        - 80
      volumes:
        - $GITHUB_WORKSPACE:/var/www/html
    services:
      mysql:
        image: mysql:5.7.27
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306
        volumes:
          - $HOME/mysql:/var/lib/mysql
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Run composer install
        run: |
          composer install --prefer-dist --no-dev

      - name: Install WordPress Test Suite
        run: |
          bash bin/install-wp-tests.sh wordpress_test root root mysql latest

      - name: Install PHPUnit
        run: |
          composer global require "phpunit/phpunit=7.5.15"

      - name: Run PHPUnit
        run: |
          ~/.composer/vendor/bin/phpunit $GITHUB_WORKSPACE